#include <iostream>

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    
int main(){

    long int sum {0};
    long int before {0};
    long int now {1};
    long int next {0};

    do {
        next = now + before;
        if (next > 4000000) { break; }
        if (next % 2 == 0) { sum += next; }
        before = now;
        now = next;
    } while (next < 4000000);
    
    std::cout << "\nSum of all even-valued terms lower than 4.000.000: " << sum;
    return 0;
}
