#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
$sum = 0
$before = 0
$now = 1
Write-Host "$before " -NoNewline
Write-Host "$now " -NoNewline
do {
    $next = $now + $before
    if ($next -gt 4000000) { break }
    if ($next % 2 -eq 0) { $sum += $next }
    Write-Host "$next " -NoNewline
    $before = $now
    $now = $next
} while ($next -lt 4000000)

Write-Host "`nSum of all even-valued terms lower than 4.000.000: $sum"
